### ISSUE TITLE
Error running mpa-portable via bioconda

### ISSUE THREAD

**Issue by CarlaCristinaUranga** [compomics/meta-proteome-analyzer#29]
Hi could you please let me know why I am getting this error? Thanks!

(mpa-portable) curangalt-osx:Biofilm_proteins curanga$ mpa-portable de.mpa.cli.CmdLineInterface -xtandem 0 -msgf 1 -spectrum_files CU_2C_01.mgf -database /Users/curanga/Desktop/Biofilm_proteins/HOMD.fasta -missed_cleav 1 -prec_tol 10ppm -frag_tol 0.02Da -fragment_method 2 -output_folder /Users/curanga/Desktop/Biofilm_proteins/Out
Mon May 18 10:21:08 PDT 2020 Creating peptide index file...
Mon May 18 10:21:08 PDT 2020 Peptide index creation finished...
Mon May 18 10:21:08 PDT 2020 Indexing MS/MS spectra...
java.io.FileNotFoundException: conf/algorithm-properties.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at de.mpa.task.ResourceProperties.loadResourcesSettings(ResourceProperties.java:69)
	at de.mpa.task.ResourceProperties.<init>(ResourceProperties.java:38)
	at de.mpa.task.ResourceProperties.getInstance(ResourceProperties.java:49)
	at de.mpa.task.Task.<init>(Task.java:67)
	at de.mpa.task.instances.SpectraTask.<init>(SpectraTask.java:25)
	at de.mpa.cli.CmdLineInterface.call(CmdLineInterface.java:243)
	at de.mpa.cli.CmdLineInterface.<init>(CmdLineInterface.java:79)
	at de.mpa.cli.CmdLineInterface.main(CmdLineInterface.java:335)
java.lang.NullPointerException
	at de.mpa.client.ui.DelegateColor.getRGB(DelegateColor.java:30)
	at java.awt.Color.equals(Color.java:699)
	at java.awt.Component.firePropertyChange(Component.java:8433)
	at java.awt.Component.setForeground(Component.java:1782)
	at javax.swing.JComponent.setForeground(JComponent.java:2704)
	at org.jdesktop.swingx.plaf.basic.BasicTitledPanelUI$1.updateUI(BasicTitledPanelUI.java:196)
	at javax.swing.JLabel.<init>(JLabel.java:164)
	at javax.swing.JLabel.<init>(JLabel.java:194)
	at org.jdesktop.swingx.plaf.basic.BasicTitledPanelUI$1.<init>(BasicTitledPanelUI.java:191)
	at org.jdesktop.swingx.plaf.basic.BasicTitledPanelUI.createAndConfigureCaption(BasicTitledPanelUI.java:191)
	at org.jdesktop.swingx.plaf.basic.BasicTitledPanelUI.installUI(BasicTitledPanelUI.java:134)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at javax.swing.JPanel.setUI(JPanel.java:153)
	at org.jdesktop.swingx.JXTitledPanel.setUI(JXTitledPanel.java:153)
	at org.jdesktop.swingx.JXTitledPanel.updateUI(JXTitledPanel.java:180)
	at javax.swing.JPanel.<init>(JPanel.java:86)
	at javax.swing.JPanel.<init>(JPanel.java:109)
	at javax.swing.JPanel.<init>(JPanel.java:117)
	at org.jdesktop.swingx.JXPanel.<init>(JXPanel.java:128)
	at org.jdesktop.swingx.JXTitledPanel.<init>(JXTitledPanel.java:127)
	at de.mpa.client.ui.PanelConfig$2.<init>(PanelConfig.java:117)
	at de.mpa.client.ui.PanelConfig.createTitledPanel(PanelConfig.java:117)
	at de.mpa.client.ui.PanelConfig.createTitledPanel(PanelConfig.java:104)
	at de.mpa.client.ui.panels.ProjectPanel.initComponents(ProjectPanel.java:179)
	at de.mpa.client.ui.panels.ProjectPanel.<init>(ProjectPanel.java:144)
	at de.mpa.client.ui.ClientFrame.initComponents(ClientFrame.java:246)
	at de.mpa.client.ui.ClientFrame.<init>(ClientFrame.java:165)
	at de.mpa.client.ui.ClientFrame.getInstance(ClientFrame.java:136)
	at de.mpa.client.ui.ClientFrame.getInstance(ClientFrame.java:126)
	at de.mpa.task.ResourceProperties.getInstance(ResourceProperties.java:52)
	at de.mpa.task.Task.<init>(Task.java:67)
	at de.mpa.task.instances.SpectraTask.<init>(SpectraTask.java:25)
	at de.mpa.cli.CmdLineInterface.call(CmdLineInterface.java:243)
	at de.mpa.cli.CmdLineInterface.<init>(CmdLineInterface.java:79)
	at de.mpa.cli.CmdLineInterface.main(CmdLineInterface.java:335)
(mpa-portable) curangalt-osx:Biofilm_proteins curanga$

**Comment by bernt-matthias** [comment]
In the Galaxy wrapper for mpa portable we do the following: 

```
        jar_dir=`mpa-portable -get_jar_dir` &&
        cp -R \$jar_dir/conf .
```

see https://github.com/galaxyproteomics/tools-galaxyp/blob/47e292d0874e5cf21ffcf886796163edac14bd2e/tools/meta_proteome_analyzer/meta_proteome_analyzer.xml#L16
