### ISSUE TITLE
mpa-portable crashed when creating FASTA index file

### ISSUE THREAD

**Issue by zhanxw** [compomics/meta-proteome-analyzer#33]
Hello, 

I am using the latest mpa-portable (mpa-portable-2.0.0) from conda.
The input FASTA file and MGF file are from Zenodo depository: https://zenodo.org/record/3727600#.YEBYjC1h0Wo
Is the error related to the FASTA header line `sp|B0CLF8|tRNA-cytidine(32) 2-sulfurtransferase`?

```

mpa-portable de.mpa.cli.CmdLineInterface  -spectrum_files FASP_BGP_A.mgf -database UniprotSwP-2020_03.fasta  -missed_cleav 1 -prec_tol 10ppm  -frag_tol 0.5Da -output_folder  output
Wed Mar 03 23:23:44 CST 2021 Creating FASTA index file...
java.lang.StringIndexOutOfBoundsException: Unable to process FASTA header line:
'sp|B0CLF8|tRNA-cytidine(32) 2-sulfurtransferase'
as a 'Generic_Header' header.
Process cancelled.
	at com.compomics.util.protein.Header.parseFromFASTA(Header.java:991)
	at de.mpa.io.fasta.FastaLoader.loadFastaFile(FastaLoader.java:265)
	at de.mpa.cli.CmdLineInterface.call(CmdLineInterface.java:202)
	at de.mpa.cli.CmdLineInterface.<init>(CmdLineInterface.java:79)
	at de.mpa.cli.CmdLineInterface.main(CmdLineInterface.java:335)

```

**Comment by zhanxw** [comment]
I fixed it after replaced ">sp" to ">generic" according to this issue in SearchGUI (https://github.com/compomics/searchgui/issues/209)
